
SELECT LTRIM('		OLÁ') AS RESULTADO;

SELECT RTRIM('OLÁ		') AS RESULTADO;

SELECT TRIM('	OLÁ 	') AS RESULTADO;

SELECT CONCAT('OLÁ',' ', 'TUDO BEM','?') AS RESULTADO;

SELECT UPPER('Olá tudo bem?') AS RESULTADO;

SELECT SUBSTRING('OLÁ, TUDO BEM?',6) AS RESULTADO;

SELECT SUBSTRING('OLÁ, TUDO BEM?',6,4) AS RESULTADO;

SELECT CONCAT(NOME, ' (', CPF, ') ') AS RESULTADO FROM tabela_de_clientes;